### PR TITLE
Fix: Admin lesson file download link page crash

### LINKED ISSUE #2896: admin screen: Clicked a file link to download and an error screen displayed
Tasks, Issues, Risks, Lessons
Screenshot Example

admin_lessons_clicked_file_link_to_download_error_screen_displayed

### PR DESCRIPTION
**Pull request by vinkMHllc**
Resolves #2896
Before:
Screenshot 2021-07-16 at 6 34 08 AM 
After:
Screenshot 2021-07-16 at 6 32 57 AM

### CODE REVIEW

File: app/admin/lessons.rb [hunk 1]
```diff
@@ -56,11 +56,7 @@
       lesson.lesson_files.map do |file|
         next if file.nil? || !file.blob.filename.instance_variable_get("@filename").present?
         if current_user.admin_write?
-          if file.blob.content_type == "text/plain"
-            link_to file.blob.filename.instance_variable_get("@filename"), file.blob.filename.instance_variable_get("@filename"), target: '_blank'
-          else
-            link_to "#{file.blob.filename}", "#{Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true)}", target: '_blank'
-          end
+          link_to "#{file.blob.filename}", "#{Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true)}", target: '_blank'
```
Comment (microhealthamand) [inline app/admin/lessons.rb:59]: Just to confirm, 
tasks issues and risks, They all have same implementation. We are saving links in plain text content type
https://github.com/MicroHealthLLC/mPATH/blob/master/app/models/lesson.rb#L37

**Comment by microhealthamand** [comment]
:+1:

**Review by microhealthamand — APPROVED** [review]

**Review by christopherandrewcalderon — APPROVED** [review]
